{
  "openapi": "3.0.0",
  "info": {
    "title": "Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc - RPC Operations",
    "description": "Copyright (c) 2019-2020 by Cisco Systems, Inc.\n     All rights reserved.\n\n**Module:** `Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc`\n**Version:** 2021-11-01\n**Operations:** 8",
    "version": "2021-11-01"
  },
  "servers": [
    {
      "url": "https://{device}/restconf",
      "variables": {
        "device": {
          "default": "devnetsandboxiosxec9k.cisco.com"
        }
      }
    }
  ],
  "paths": {
    "/operations/wireless_ble_mgmt_cmd_rpc:ble-sync-req": {
      "post": {
        "summary": "Command to send a BLE sync request",
        "description": "Command to send a BLE sync request\n\n**Endpoint:** `POST /restconf/operations/wireless_ble_mgmt_cmd_rpc:ble-sync-req`",
        "operationId": "post-root-7",
        "tags": [
          "Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_ble_mgmt_cmd_rpc:ble-sync-req": {
                    "type": "object",
                    "properties": {
                      "ble-mac": {
                        "type": "string",
                        "description": "BLE MAC address",
                        "example": "00:1a:2b:3c:4d:5e"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name",
                        "example": "example-1"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "MAC address",
                        "example": "00:1a:2b:3c:4d:5e"
                      }
                    },
                    "required": [
                      "ble-mac"
                    ],
                    "example": "configured-value"
                  }
                },
                "example": "configured-value"
              },
              "example": {
                "wireless_ble_mgmt_cmd_rpc:ble-sync-req": {
                  "ble-mac": "00:11:22:33:44:55",
                  "ap-name": "example-1",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_ble_mgmt_cmd_rpc:ble-sync-req": {
                      "type": "object",
                      "example": "configured-value"
                    }
                  },
                  "example": "configured-value"
                },
                "example": {
                  "wireless_ble_mgmt_cmd_rpc:ble-sync-req": {
                    "wireless_ble_mgmt_cmd_rpc:ble-sync-req": [
                      null
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_ble_mgmt_cmd_rpc:ble-scan-req": {
      "post": {
        "summary": "Command to configure BLE scan role",
        "description": "Command to configure BLE scan role\n\n**Endpoint:** `POST /restconf/operations/wireless_ble_mgmt_cmd_rpc:ble-scan-req`",
        "operationId": "post-root-6",
        "tags": [
          "Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_ble_mgmt_cmd_rpc:ble-scan-req": {
                    "type": "object",
                    "properties": {
                      "interval-sec": {
                        "type": "string",
                        "description": "Scan interval",
                        "example": "configured-value"
                      },
                      "window-msec": {
                        "type": "string",
                        "description": "Scan window",
                        "example": "configured-value"
                      },
                      "max-value": {
                        "type": "string",
                        "description": "Scan max value",
                        "example": "configured-value"
                      },
                      "filter": {
                        "type": "string",
                        "description": "Scan filter",
                        "example": "configured-value"
                      },
                      "state": {
                        "type": "string",
                        "description": "Scan state",
                        "example": "active"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name",
                        "example": "example-1"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "MAC address",
                        "example": "00:1a:2b:3c:4d:5e"
                      }
                    },
                    "required": [
                      "interval-sec",
                      "state"
                    ],
                    "example": "configured-value"
                  }
                },
                "example": "configured-value"
              },
              "example": {
                "wireless_ble_mgmt_cmd_rpc:ble-scan-req": {
                  "interval-sec": "configured-value",
                  "window-msec": "configured-value",
                  "max-value": "configured-value",
                  "filter": "configured-value",
                  "state": "active",
                  "ap-name": "example-1",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_ble_mgmt_cmd_rpc:ble-scan-req": {
                      "type": "object",
                      "example": "configured-value"
                    }
                  },
                  "example": "configured-value"
                },
                "example": {
                  "wireless_ble_mgmt_cmd_rpc:ble-scan-req": {
                    "wireless_ble_mgmt_cmd_rpc:ble-scan-req": [
                      null
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_ble_mgmt_cmd_rpc:ble-ibeacon-req": {
      "post": {
        "summary": "Command to configure BLE beacon of type iBeacon",
        "description": "Command to configure BLE beacon of type iBeacon\n\n**Endpoint:** `POST /restconf/operations/wireless_ble_mgmt_cmd_rpc:ble-ibeacon-req`",
        "operationId": "post-root-3",
        "tags": [
          "Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_ble_mgmt_cmd_rpc:ble-ibeacon-req": {
                    "type": "object",
                    "properties": {
                      "uuid": {
                        "type": "string",
                        "description": "UUID to be chirped by the beacon of type iBeacon",
                        "example": "1"
                      },
                      "major": {
                        "type": "string",
                        "description": "Major value to be chirped by the beacon of type iBeacon",
                        "example": "configured-value"
                      },
                      "minor": {
                        "type": "string",
                        "description": "Minor value to be chirped by the beacon of type iBeacon",
                        "example": "configured-value"
                      },
                      "tx-power": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 12,
                        "description": "Power to chirp with for the beacon of type iBeacon",
                        "example": 1
                      },
                      "frequency-msec": {
                        "type": "integer",
                        "minimum": 100,
                        "maximum": 1000,
                        "description": "Frequency to chirp with for the beacon of type iBeacon",
                        "example": 1
                      },
                      "adv-tx-power": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 127,
                        "description": "Power to advertise when chirping beacon of type iBeacon",
                        "example": 1
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name",
                        "example": "example-1"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "MAC address",
                        "example": "00:1a:2b:3c:4d:5e"
                      }
                    },
                    "required": [
                      "uuid",
                      "major",
                      "minor",
                      "tx-power",
                      "frequency-msec",
                      "adv-tx-power"
                    ],
                    "example": "configured-value"
                  }
                },
                "example": "configured-value"
              },
              "example": {
                "wireless_ble_mgmt_cmd_rpc:ble-ibeacon-req": {
                  "uuid": "1",
                  "major": "configured-value",
                  "minor": "configured-value",
                  "tx-power": 10,
                  "frequency-msec": 100,
                  "adv-tx-power": 10,
                  "ap-name": "example-1",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_ble_mgmt_cmd_rpc:ble-ibeacon-req": {
                      "type": "object",
                      "example": "configured-value"
                    }
                  },
                  "example": "configured-value"
                },
                "example": {
                  "wireless_ble_mgmt_cmd_rpc:ble-ibeacon-req": {
                    "wireless_ble_mgmt_cmd_rpc:ble-ibeacon-req": [
                      null
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_ble_mgmt_cmd_rpc:ble-eddy-uid-req": {
      "post": {
        "summary": "Command to configure BLE Eddystone UID beacon",
        "description": "Command to configure BLE Eddystone UID beacon\n\n**Endpoint:** `POST /restconf/operations/wireless_ble_mgmt_cmd_rpc:ble-eddy-uid-req`",
        "operationId": "post-root",
        "tags": [
          "Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_ble_mgmt_cmd_rpc:ble-eddy-uid-req": {
                    "type": "object",
                    "properties": {
                      "instance-id": {
                        "type": "string",
                        "description": "Instance ID to be chirped by the Eddystone UID beacon",
                        "example": "1"
                      },
                      "namespace": {
                        "type": "string",
                        "description": "Namespace to be chirped by the Eddystone UID beacon",
                        "example": "example-1"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name",
                        "example": "example-1"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "MAC address",
                        "example": "00:1a:2b:3c:4d:5e"
                      }
                    },
                    "required": [
                      "instance-id",
                      "namespace"
                    ],
                    "example": 1
                  }
                },
                "example": 1
              },
              "example": {
                "wireless_ble_mgmt_cmd_rpc:ble-eddy-uid-req": {
                  "instance-id": "1",
                  "namespace": "example-1",
                  "ap-name": "example-1",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_ble_mgmt_cmd_rpc:ble-eddy-uid-req": {
                      "type": "object",
                      "example": 1
                    }
                  },
                  "example": 1
                },
                "example": {
                  "wireless_ble_mgmt_cmd_rpc:ble-eddy-uid-req": {
                    "wireless_ble_mgmt_cmd_rpc:ble-eddy-uid-req": 1
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_ble_mgmt_cmd_rpc:ble-eddy-url-req": {
      "post": {
        "summary": "Command to configure BLE Eddystone URL beacon",
        "description": "Command to configure BLE Eddystone URL beacon\n\n**Endpoint:** `POST /restconf/operations/wireless_ble_mgmt_cmd_rpc:ble-eddy-url-req`",
        "operationId": "post-root-2",
        "tags": [
          "Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_ble_mgmt_cmd_rpc:ble-eddy-url-req": {
                    "type": "object",
                    "properties": {
                      "url": {
                        "type": "string",
                        "description": "URL to be chirped by the Eddystone URL beacon",
                        "example": "https://10.1.1.1/restconf"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name",
                        "example": "example-1"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "MAC address",
                        "example": "00:1a:2b:3c:4d:5e"
                      }
                    },
                    "required": [
                      "url"
                    ],
                    "example": "https://10.1.1.1/restconf"
                  }
                },
                "example": "https://10.1.1.1/restconf"
              },
              "example": {
                "wireless_ble_mgmt_cmd_rpc:ble-eddy-url-req": {
                  "url": "flash:/config.txt",
                  "ap-name": "example-1",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_ble_mgmt_cmd_rpc:ble-eddy-url-req": {
                      "type": "object",
                      "example": "https://10.1.1.1/restconf"
                    }
                  },
                  "example": "https://10.1.1.1/restconf"
                },
                "example": {
                  "wireless_ble_mgmt_cmd_rpc:ble-eddy-url-req": {
                    "wireless_ble_mgmt_cmd_rpc:ble-eddy-url-req": "https://10.1.1.1/restconf"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_ble_mgmt_cmd_rpc:ble-mgt-admin-req": {
      "post": {
        "summary": "Command to enable or disable BLE functionality",
        "description": "Command to enable or disable BLE functionality\n\n**Endpoint:** `POST /restconf/operations/wireless_ble_mgmt_cmd_rpc:ble-mgt-admin-req`",
        "operationId": "post-root-4",
        "tags": [
          "Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_ble_mgmt_cmd_rpc:ble-mgt-admin-req": {
                    "type": "object",
                    "properties": {
                      "state": {
                        "type": "string",
                        "description": "BLE admin flag",
                        "example": "active"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name",
                        "example": "example-1"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "MAC address",
                        "example": "00:1a:2b:3c:4d:5e"
                      }
                    },
                    "required": [
                      "state"
                    ],
                    "example": "configured-value"
                  }
                },
                "example": "configured-value"
              },
              "example": {
                "wireless_ble_mgmt_cmd_rpc:ble-mgt-admin-req": {
                  "state": "active",
                  "ap-name": "example-1",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_ble_mgmt_cmd_rpc:ble-mgt-admin-req": {
                      "type": "object",
                      "example": "configured-value"
                    }
                  },
                  "example": "configured-value"
                },
                "example": {
                  "wireless_ble_mgmt_cmd_rpc:ble-mgt-admin-req": {
                    "wireless_ble_mgmt_cmd_rpc:ble-mgt-admin-req": [
                      null
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_ble_mgmt_cmd_rpc:ble-vibeacon-req": {
      "post": {
        "summary": "Command to configure BLE beacon of type viBeacon",
        "description": "Command to configure BLE beacon of type viBeacon\n\n**Endpoint:** `POST /restconf/operations/wireless_ble_mgmt_cmd_rpc:ble-vibeacon-req`",
        "operationId": "post-root-8",
        "tags": [
          "Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_ble_mgmt_cmd_rpc:ble-vibeacon-req": {
                    "type": "object",
                    "properties": {
                      "beacon-id": {
                        "type": "string",
                        "description": "Id of the viBeacon being configured",
                        "example": "1"
                      },
                      "status": {
                        "type": "string",
                        "description": "Status of the viBeacon being configured",
                        "example": "active"
                      },
                      "uuid": {
                        "type": "string",
                        "description": "UUID to be chirped by the beacon of type viBeacon",
                        "example": "1"
                      },
                      "major": {
                        "type": "string",
                        "description": "Type (major value) to be chirped by the beacon of type viBeacon",
                        "example": "configured-value"
                      },
                      "minor": {
                        "type": "string",
                        "description": "Subtype (minor value) to be chirped by the beacon of type viBeacon",
                        "example": "configured-value"
                      },
                      "tx-power": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 12,
                        "description": "Power to chirp with for the beacon of type viBeacon",
                        "example": 1
                      },
                      "interval-msec": {
                        "type": "integer",
                        "minimum": 100,
                        "maximum": 1000,
                        "description": "Interval to chirp with for the beacon of type viBeacon",
                        "example": 1
                      },
                      "adv-tx-power": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 127,
                        "description": "Power to advertise when chirping beacon of type viBeacon",
                        "example": 1
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name",
                        "example": "example-1"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "MAC address",
                        "example": "00:1a:2b:3c:4d:5e"
                      }
                    },
                    "required": [
                      "beacon-id",
                      "status",
                      "uuid",
                      "major",
                      "minor",
                      "tx-power",
                      "interval-msec",
                      "adv-tx-power"
                    ],
                    "example": "configured-value"
                  }
                },
                "example": "configured-value"
              },
              "example": {
                "wireless_ble_mgmt_cmd_rpc:ble-vibeacon-req": {
                  "beacon-id": "1",
                  "status": "active",
                  "uuid": "1",
                  "major": "configured-value",
                  "minor": "configured-value",
                  "tx-power": 10,
                  "interval-msec": 100,
                  "adv-tx-power": 10,
                  "ap-name": "example-1",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_ble_mgmt_cmd_rpc:ble-vibeacon-req": {
                      "type": "object",
                      "example": "configured-value"
                    }
                  },
                  "example": "configured-value"
                },
                "example": {
                  "wireless_ble_mgmt_cmd_rpc:ble-vibeacon-req": {
                    "wireless_ble_mgmt_cmd_rpc:ble-vibeacon-req": [
                      null
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_ble_mgmt_cmd_rpc:ble-no-adv-profile-req": {
      "post": {
        "summary": "RPC to configure BLE no advertisement profile",
        "description": "RPC to configure BLE no advertisement profile\n\n**Endpoint:** `POST /restconf/operations/wireless_ble_mgmt_cmd_rpc:ble-no-adv-profile-req`",
        "operationId": "post-root-5",
        "tags": [
          "Cisco-IOS-XE-wireless-ble-mgmt-cmd-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_ble_mgmt_cmd_rpc:ble-no-adv-profile-req": {
                    "type": "object",
                    "properties": {
                      "state": {
                        "type": "string",
                        "description": "No advertisement profile state",
                        "example": "active"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name",
                        "example": "example-1"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "MAC address",
                        "example": "00:1a:2b:3c:4d:5e"
                      }
                    },
                    "required": [
                      "state"
                    ],
                    "example": "configured-value"
                  }
                },
                "example": "configured-value"
              },
              "example": {
                "wireless_ble_mgmt_cmd_rpc:ble-no-adv-profile-req": {
                  "state": "active",
                  "ap-name": "example-1",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_ble_mgmt_cmd_rpc:ble-no-adv-profile-req": {
                      "type": "object",
                      "example": "configured-value"
                    }
                  },
                  "example": "configured-value"
                },
                "example": {
                  "wireless_ble_mgmt_cmd_rpc:ble-no-adv-profile-req": {
                    "wireless_ble_mgmt_cmd_rpc:ble-no-adv-profile-req": [
                      null
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "security": [
    {
      "basicAuth": []
    }
  ]
}
