{
  "openapi": "3.0.0",
  "info": {
    "title": "Cisco-IOS-XE-wireless-mesh-rpc - RPC Operations",
    "description": "This module contains a collection of definitions for\n     Wireless Mesh Remote Procedure Calls.\n     Copyright (c) 2021-2022 by Cisco Systems, Inc.\n     All rights reserved.\n\n**Module:** `Cisco-IOS-XE-wireless-mesh-rpc`\n**Version:** 2022-07-01\n**Operations:** 19",
    "version": "2022-07-01"
  },
  "servers": [
    {
      "url": "https://{device}/restconf",
      "variables": {
        "device": {
          "default": "router.example.com"
        }
      }
    }
  ],
  "paths": {
    "/operations/wireless_mesh_rpc:rrm-80211a-channel-update-mesh": {
      "post": {
        "summary": "Trigger RRM DCA run for Mesh backhaul for all RAP on 5GHz band",
        "description": "Trigger RRM DCA run for Mesh backhaul for all RAP on 5GHz band\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:rrm-80211a-channel-update-mesh`",
        "operationId": "post-root-3",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:rrm-80211a-channel-update-mesh": {
                    "type": "object",
                    "properties": {}
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:rrm-80211a-channel-update-mesh": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:rrm-80211a-channel-update-mesh": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:rrm-80211a-channel-update-mesh": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:rrm-80211b-channel-update-mesh": {
      "post": {
        "summary": "Trigger RRM DCA run for Mesh backhaul for all RAP on 2.4GHz band",
        "description": "Trigger RRM DCA run for Mesh backhaul for all RAP on 2.4GHz band\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:rrm-80211b-channel-update-mesh`",
        "operationId": "post-root-6",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:rrm-80211b-channel-update-mesh": {
                    "type": "object",
                    "properties": {}
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:rrm-80211b-channel-update-mesh": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:rrm-80211b-channel-update-mesh": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:rrm-80211b-channel-update-mesh": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:rrm-80211a-channel-update-mesh-bgn": {
      "post": {
        "summary": "Trigger RRM DCA run for Mesh backhaul for all RAP in bridge group on 5GHz band",
        "description": "Trigger RRM DCA run for Mesh backhaul for all RAP in bridge group on 5GHz band\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:rrm-80211a-channel-update-mesh-bgn`",
        "operationId": "post-root-4",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:rrm-80211a-channel-update-mesh-bgn": {
                    "type": "object",
                    "properties": {
                      "bgn-name": {
                        "type": "string",
                        "description": "Bridge Group name"
                      }
                    },
                    "required": [
                      "bgn-name"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:rrm-80211a-channel-update-mesh-bgn": {
                  "bgn-name": "example-string"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:rrm-80211a-channel-update-mesh-bgn": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:rrm-80211a-channel-update-mesh-bgn": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:rrm-80211b-channel-update-mesh-bgn": {
      "post": {
        "summary": "Trigger RRM DCA run for Mesh backhaul for all RAP in bridge group on 2.4GHz band",
        "description": "Trigger RRM DCA run for Mesh backhaul for all RAP in bridge group on 2.4GHz band\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:rrm-80211b-channel-update-mesh-bgn`",
        "operationId": "post-root-7",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:rrm-80211b-channel-update-mesh-bgn": {
                    "type": "object",
                    "properties": {
                      "bgn-name": {
                        "type": "string",
                        "description": "Bridge Group name"
                      }
                    },
                    "required": [
                      "bgn-name"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:rrm-80211b-channel-update-mesh-bgn": {
                  "bgn-name": "example-string"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:rrm-80211b-channel-update-mesh-bgn": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:rrm-80211b-channel-update-mesh-bgn": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:exec-linktest-ap": {
      "post": {
        "summary": "Perform link test between 2 bridge mode APs",
        "description": "Perform link test between 2 bridge mode APs\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:exec-linktest-ap`",
        "operationId": "post-root",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:exec-linktest-ap": {
                    "type": "object",
                    "properties": {
                      "dst-ap-mac": {
                        "type": "string",
                        "description": "Radio MAC address of the destination AP"
                      },
                      "pkt-per-sec": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 25000,
                        "description": "Packet rate"
                      },
                      "pkt-size": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 1500,
                        "description": "Size of packets for link test"
                      },
                      "duration": {
                        "type": "integer",
                        "minimum": 10,
                        "maximum": 300,
                        "description": "Total link test duration"
                      },
                      "data-rate-idx": {
                        "type": "string",
                        "description": "Dot11a/b/g data rate index"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "Source AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "Source AP radio MAC address"
                      }
                    },
                    "required": [
                      "dst-ap-mac",
                      "pkt-per-sec",
                      "pkt-size",
                      "duration",
                      "data-rate-idx",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:exec-linktest-ap": {
                  "dst-ap-mac": "00:11:22:33:44:55",
                  "pkt-per-sec": 10,
                  "pkt-size": 10,
                  "duration": 10,
                  "data-rate-idx": "example-string",
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:exec-linktest-ap": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:exec-linktest-ap": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-security-psk-provisioning-delete": {
      "post": {
        "summary": "Delete the provisioned PSK key on a bridge mode AP",
        "description": "Delete the provisioned PSK key on a bridge mode AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-security-psk-provisioning-delete`",
        "operationId": "post-root-17",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-security-psk-provisioning-delete": {
                    "type": "object",
                    "properties": {
                      "ap-name": {
                        "type": "string",
                        "description": "AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "AP Radio MAC address"
                      }
                    },
                    "required": [
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-security-psk-provisioning-delete": {
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-security-psk-provisioning-delete": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-security-psk-provisioning-delete": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-preferred-parent-ap": {
      "post": {
        "summary": "Configure the preferred parent of a mesh AP",
        "description": "Configure the preferred parent of a mesh AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-preferred-parent-ap`",
        "operationId": "post-root-16",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-preferred-parent-ap": {
                    "type": "object",
                    "properties": {
                      "mac-address": {
                        "type": "string",
                        "description": "Radio MAC address of the preferred parent"
                      },
                      "enable": {
                        "type": "string",
                        "description": "Provision/un-provision the preferred parent"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "Mesh AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "Mesh AP radio MAC address"
                      }
                    },
                    "required": [
                      "mac-address",
                      "enable",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-preferred-parent-ap": {
                  "mac-address": "00:11:22:33:44:55",
                  "enable": "example-string",
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-preferred-parent-ap": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-preferred-parent-ap": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-daisy-chain-mode": {
      "post": {
        "summary": "Configure daisy chain mode on a mesh AP",
        "description": "Configure daisy chain mode on a mesh AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-daisy-chain-mode`",
        "operationId": "post-root-11",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-daisy-chain-mode": {
                    "type": "object",
                    "properties": {
                      "daisy-chain-mode": {
                        "type": "string",
                        "description": "Enable/disable daisy chaining"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "Mesh AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "Mesh AP radio MAC address"
                      }
                    },
                    "required": [
                      "daisy-chain-mode",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-daisy-chain-mode": {
                  "daisy-chain-mode": "example-string",
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-daisy-chain-mode": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-daisy-chain-mode": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-daisy-chain-strict-rap": {
      "post": {
        "summary": "Configure strict daisy chain on a mesh AP",
        "description": "Configure strict daisy chain on a mesh AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-daisy-chain-strict-rap`",
        "operationId": "post-root-12",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-daisy-chain-strict-rap": {
                    "type": "object",
                    "properties": {
                      "daisy-chain-strict-rap": {
                        "type": "string",
                        "description": "Provision/un-provision strict daisy chain mode"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "Mesh AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "Mesh AP radio MAC address"
                      }
                    },
                    "required": [
                      "daisy-chain-strict-rap",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-daisy-chain-strict-rap": {
                  "daisy-chain-strict-rap": "example-string",
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-daisy-chain-strict-rap": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-daisy-chain-strict-rap": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-block-child": {
      "post": {
        "summary": "Configure block child mode on a bridge mode AP",
        "description": "Configure block child mode on a bridge mode AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-block-child`",
        "operationId": "post-root-10",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-block-child": {
                    "type": "object",
                    "properties": {
                      "block-child-state": {
                        "type": "string",
                        "description": "Enable/Disable block child mode"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "AP radio MAC address"
                      }
                    },
                    "required": [
                      "block-child-state",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-block-child": {
                  "block-child-state": "example-string",
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-block-child": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-block-child": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-bhaul-radio": {
      "post": {
        "summary": "Configure the backhaul radio of a bridge mode AP",
        "description": "Configure the backhaul radio of a bridge mode AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-bhaul-radio`",
        "operationId": "post-root-8",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-bhaul-radio": {
                    "type": "object",
                    "properties": {
                      "bhaul-slot-id": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 3,
                        "description": "Backhaul radio slot ID"
                      },
                      "bhaul-radio-band": {
                        "type": "string",
                        "description": "Backhaul radio band"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "AP radio MAC address"
                      }
                    },
                    "required": [
                      "bhaul-slot-id",
                      "bhaul-radio-band",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-bhaul-radio": {
                  "bhaul-slot-id": 3,
                  "bhaul-radio-band": "example-string",
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-bhaul-radio": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-bhaul-radio": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-bhaul-tx-rate": {
      "post": {
        "summary": "Configure the backhaul transmission parameters of a bridge mode AP",
        "description": "Configure the backhaul transmission parameters of a bridge mode AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-bhaul-tx-rate`",
        "operationId": "post-root-9",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-bhaul-tx-rate": {
                    "type": "object",
                    "properties": {
                      "bhaul-rate-mcs-index": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 31,
                        "description": "Backhaul transmission MCS rate index"
                      },
                      "spatial-stream": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 8,
                        "description": "Mesh backhaul 802.11ac spatial stream"
                      },
                      "data-rate": {
                        "type": "string",
                        "description": "802.11 data rate. Set to auto or manually select 802.11abg/n/ac"
                      },
                      "bhaul-tx-rate-type": {
                        "type": "string",
                        "description": "Valid 802.11a/b/g data rate"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "AP radio MAC address"
                      }
                    },
                    "required": [
                      "bhaul-rate-mcs-index",
                      "spatial-stream",
                      "data-rate",
                      "bhaul-tx-rate-type",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-bhaul-tx-rate": {
                  "bhaul-rate-mcs-index": 10,
                  "spatial-stream": 8,
                  "data-rate": "example-string",
                  "bhaul-tx-rate-type": "example-string",
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-bhaul-tx-rate": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-bhaul-tx-rate": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:rrm-80211b-ap-rrm-channel-update-mesh": {
      "post": {
        "summary": "Trigger RRM DCA run for Mesh backhaul for RAP on 2.4GHz band",
        "description": "Trigger RRM DCA run for Mesh backhaul for RAP on 2.4GHz band\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:rrm-80211b-ap-rrm-channel-update-mesh`",
        "operationId": "post-root-5",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:rrm-80211b-ap-rrm-channel-update-mesh": {
                    "type": "object",
                    "properties": {
                      "ap-name": {
                        "type": "string",
                        "description": "Mesh AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "Mesh AP radio MAC address"
                      }
                    },
                    "required": [
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:rrm-80211b-ap-rrm-channel-update-mesh": {
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:rrm-80211b-ap-rrm-channel-update-mesh": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:rrm-80211b-ap-rrm-channel-update-mesh": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:rrm-80211a-ap-rrm-channel-update-mesh": {
      "post": {
        "summary": "Trigger RRM DCA run for Mesh backhaul for RAP on 5GHz band",
        "description": "Trigger RRM DCA run for Mesh backhaul for RAP on 5GHz band\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:rrm-80211a-ap-rrm-channel-update-mesh`",
        "operationId": "post-root-2",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:rrm-80211a-ap-rrm-channel-update-mesh": {
                    "type": "object",
                    "properties": {
                      "ap-name": {
                        "type": "string",
                        "description": "Mesh AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "Mesh AP radio MAC address"
                      }
                    },
                    "required": [
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:rrm-80211a-ap-rrm-channel-update-mesh": {
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:rrm-80211a-ap-rrm-channel-update-mesh": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:rrm-80211a-ap-rrm-channel-update-mesh": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-trunking-vlan": {
      "post": {
        "summary": "Configure the trunk VLAN port on a bridge mode AP",
        "description": "Configure the trunk VLAN port on a bridge mode AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-trunking-vlan`",
        "operationId": "post-root-19",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-trunking-vlan": {
                    "type": "object",
                    "properties": {
                      "vlan-id": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 4094,
                        "description": "VLAN ID to be configured on primary port"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "AP radio MAC address"
                      }
                    },
                    "required": [
                      "vlan-id",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-trunking-vlan": {
                  "vlan-id": 100,
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-trunking-vlan": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-trunking-vlan": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-trunking": {
      "post": {
        "summary": "Configure VLAN trunking on a bridge mode AP",
        "description": "Configure VLAN trunking on a bridge mode AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-trunking`",
        "operationId": "post-root-18",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-trunking": {
                    "type": "object",
                    "properties": {
                      "flag": {
                        "type": "string",
                        "description": "Enable/Disable VLAN trunking"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "AP radio MAC address"
                      }
                    },
                    "required": [
                      "flag",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-trunking": {
                  "flag": "example-string",
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-trunking": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-trunking": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-ethernet-access-vlan": {
      "post": {
        "summary": "Configure access VLAN on a bridge mode AP ethernet port",
        "description": "Configure access VLAN on a bridge mode AP ethernet port\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-ethernet-access-vlan`",
        "operationId": "post-root-13",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-ethernet-access-vlan": {
                    "type": "object",
                    "properties": {
                      "flag": {
                        "type": "string",
                        "description": "Enable/Disable access mode for an ethernet port"
                      },
                      "port-num": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 3,
                        "description": "Ethernet port number to be configured"
                      },
                      "vlan-id": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 4094,
                        "description": "Set VLAN ID of access port. 0 is the default VLAN"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "AP radio MAC address"
                      }
                    },
                    "required": [
                      "flag",
                      "port-num",
                      "vlan-id",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-ethernet-access-vlan": {
                  "flag": "example-string",
                  "port-num": 8080,
                  "vlan-id": 100,
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-ethernet-access-vlan": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-ethernet-access-vlan": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-native-vlan": {
      "post": {
        "summary": "Configure native VLAN for a trunk ethernet port on a bridge mode AP",
        "description": "Configure native VLAN for a trunk ethernet port on a bridge mode AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-native-vlan`",
        "operationId": "post-root-15",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-native-vlan": {
                    "type": "object",
                    "properties": {
                      "flag": {
                        "type": "string",
                        "description": "Enable/Disable trunk mode for an ethernet port"
                      },
                      "port-num": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 3,
                        "description": "Ethernet port number to be configured"
                      },
                      "vlan-id": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 4094,
                        "description": "Set native VLAN ID of trunking port"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "AP radio MAC address"
                      }
                    },
                    "required": [
                      "flag",
                      "port-num",
                      "vlan-id",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-native-vlan": {
                  "flag": "example-string",
                  "port-num": 8080,
                  "vlan-id": 100,
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-native-vlan": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-native-vlan": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/operations/wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-allowed-vlan": {
      "post": {
        "summary": "Configure allowed VLAN for a trunk ethernet port on a bridge mode AP",
        "description": "Configure allowed VLAN for a trunk ethernet port on a bridge mode AP\n\n**Endpoint:** `POST /restconf/operations/wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-allowed-vlan`",
        "operationId": "post-root-14",
        "tags": [
          "Cisco-IOS-XE-wireless-mesh-rpc"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/yang-data+json": {
              "schema": {
                "type": "object",
                "properties": {
                  "wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-allowed-vlan": {
                    "type": "object",
                    "properties": {
                      "flag": {
                        "type": "string",
                        "description": "Add/remove allowed VLAN to/from trunk port"
                      },
                      "port-num": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 3,
                        "description": "Ethernet port number of trunk port"
                      },
                      "vlan-id": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 4094,
                        "description": "Set allowed VLAN ID of trunk port. 0 is the default VLAN"
                      },
                      "ap-name": {
                        "type": "string",
                        "description": "AP name"
                      },
                      "mac-addr": {
                        "type": "string",
                        "description": "AP radio MAC address"
                      }
                    },
                    "required": [
                      "flag",
                      "port-num",
                      "vlan-id",
                      "ap-name",
                      "mac-addr"
                    ]
                  }
                }
              },
              "example": {
                "wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-allowed-vlan": {
                  "flag": "example-string",
                  "port-num": 8080,
                  "vlan-id": 100,
                  "ap-name": "example-string",
                  "mac-addr": "00:11:22:33:44:55"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "RPC executed successfully",
            "content": {
              "application/yang-data+json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-allowed-vlan": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "wireless_mesh_rpc:set-rad-mesh-ethernet-trunk-allowed-vlan": {}
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "security": [
    {
      "basicAuth": []
    }
  ]
}
